# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tagcloud

# Miscellaneous
google_analytics: UA-16648317-8
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: